scrape_configs:
  - job_name: node
    scrape_interval: 5s
    static_configs:
    - targets: ['node-exporter:9100']
  - job_name: php-fpm
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.112.125:9253']
  - job_name: mariadb
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.112.125:9104']
  - job_name: nginx
    static_configs:
      - targets: ['192.168.112.125:9113']
  - job_name: wordpress_exporter
    honor_timestamps: true
    scrape_interval: 60s
    scrape_timeout: 15s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ["192.168.112.125:11011"]

rule_files:
  - 'alert.rules'

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"
